Revert "Switch to SSH key signing"
This reverts commit 94161bf9a3c541370762a06ab3fed1c1c522e8b4.

```log
error: Error: AppError { error: Os { code: 2, kind: NotFound, message: "No such file or directory" }, location: Location { file: "ssh/op-ssh-sign/src/ops.rs", line: 41, col: 52 } }

fatal: failed to write commit object
error: could not commit staged changes.
```

Signed-off-by: Matthias Rampke <matthias@rampke.de>